name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        with:
          cmd: install --frozen-lockfile --legacy-peer-deps
        uses: borales/actions-yarn@v3.0.0

      - name: Build Storybook
        with:
          cmd: build-storybook
        uses: borales/actions-yarn@v3.0.0
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Deploy Storybook
        with:
          cmd: deploy-storybook --ci --existing-output-dir=storybook-static --source-branch=main --remote=upstream
        uses: borales/actions-yarn@v3.0.0
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
