name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

        with:
            cmd: install
        - name: Install dependencies
          uses: borales/actions-yarn@v3.0.0

        with:
            cmd: build-storybook
        - name: Build Storybook
          uses: borales/actions-yarn@v3.0.0

        with:
            cmd: deploy-storybook -- --ci --existing-output-dir=storybook-static
        - name: Build Storybook
          uses: borales/actions-yarn@v3.0.0
          env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
